// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agoauhvxuloyrubwwgoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2F1aHZ4dWxveXJ1Ynd3Z29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjAzNTAsImV4cCI6MjA3Mzg5NjM1MH0.kfEbf5w0tqHPoyTgm9k_8lbQgb0wlo2A9gk5AfWS5D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});